# Generated by Django 4.1.7 on 2023-07-16 13:39

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', ckeditor_uploader.fields.RichTextUploadingField(max_length=1000000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mappingcategory')),
            ],
        ),
    ]
