# Generated by Django 4.1.7 on 2023-07-16 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_painting_options_mapping_image_mapping_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connecting',
            name='image',
            field=models.ImageField(null=True, upload_to='mapping/'),
        ),
        migrations.AddField(
            model_name='connecting',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='connecting',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mappingcategory'),
        ),
    ]
